export const industryMapping: Record<string, string> = {
    Restaurants: "Restaurants",
    Hotel: "Hotel",
    "Hospitals and Healthcare": "Hospitals_and_Healthcare",
    "Educational Institutions": "Educational_Institutions",
    Ecommerce: "Ecommerce",
    Charity: "Charity",
    "Social Media": "Social_Media",
    "Tech Manufacturing": "Tech_Manufacturing",
    Manufacturing: "Manufacturing",
    "Transportation and Warehousing": "Transportation_and_Warehousing",
    Retail: "Retail",
    Construction: "Construction",
    Insurance: "Insurance",
    Banks: "Banks",
    "Digital Lending Platforms": "Digital_Lending_Platforms",
    Agriculture: "Agriculture",
    Pharmaceutical: "Pharmaceutical",
    "Car Manufacturing": "Car_Manufacturing",
    Gaming: "Gaming",
    "Food and Beverages": "Food_and_Beverages",
    "IT Outsourcing": "IT_Outsourcing",
  };
  