"use client";

import React from 'react';
import { Shield } from 'lucide-react';
import { useRouter } from 'next/navigation';
import '../globals.css';

const faqs = [
  {
    question: "What is the DPDP Act of India?",
    answer: "The DPDP (Data Protection and Privacy) Act of India is a comprehensive legislation aimed at safeguarding the privacy and personal data of individuals. It outlines the responsibilities of organizations in handling personal data and the rights of individuals in relation to their data."
  },
  {
    question: "How does your service help in complying with the DPDP Act?",
    answer: "Our service provides an end-to-end solution for compliance with the DPDP Act. We generate a comprehensive privacy policy and a robust FAQ chatbot that ensures all required information is readily available to users, thereby reducing the compliance burden on your organization."
  },
  {
    question: "Is the privacy policy generated customizable?",
    answer: "Yes, the privacy policy generated by our service is fully customizable. You can tailor it to suit the specific needs of your organization while ensuring it remains compliant with the DPDP Act."
  },
  {
    question: "How frequently is the information updated?",
    answer: "We continuously monitor updates to the DPDP Act and other relevant regulations. Our service ensures that your privacy policy and chatbot are always up-to-date with the latest legal requirements."
  },
  {
    question: "What kind of support do you provide?",
    answer: "We offer comprehensive support to ensure you get the most out of our service. This includes setup assistance, customization help, and ongoing updates to keep your privacy policy and chatbot compliant with the latest regulations."
  }
];

const DpdpFaqsPage = () => {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-gray-100 text-gray-800">
      {/* Header */}
      <header className="px-4 lg:px-6 h-16 flex items-center justify-between border-b border-gray-200 bg-white shadow-sm">
      <div
        className="flex items-center cursor-pointer"
        onClick={() => router.push('/')}
        >
        <Shield className="h-8 w-8 text-blue-600" />
        <span className="ml-2 text-xl font-bold text-blue-600">Easy Privacy</span>
        </div>
        <div className="space-x-4">
          <button
            onClick={() => router.push('/')}
            className="text-blue-600 hover:text-blue-800 transition-colors"
          >
            Home
          </button>
          <button
            onClick={() => router.push('/policy-generator')}
            className="text-blue-600 hover:text-blue-800 transition-colors"
          >
            Policy Generator
          </button>
        </div>
      </header>

      {/* Main Content */}
      <main className="px-4 lg:px-6 py-10">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-3xl font-bold text-center text-blue-600 mb-8">Frequently Asked Questions</h1>
          {faqs.map((faq, index) => (
            <div className="faq-item mb-6" key={index}>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">{faq.question}</h3>
              <p className="text-gray-700">{faq.answer}</p>
            </div>
          ))}
        </div>
      </main>

      {/* Footer */}
      <footer className="px-4 lg:px-6 py-4 bg-white border-t border-gray-200 text-center text-gray-500">
        &copy; 2024 Easy Privacy. All rights reserved.
      </footer>
    </div>
  );
};

export default DpdpFaqsPage;
